### PR TITLE
Remove root access from ec2-user

### PR DESCRIPTION
**Pull request by saschat**
An experiment to see if it passes the tests.

Given that we don't have a proper testing and staging channel yet it is easiest to just merge, submit the AMI and if it fails revert.

### CODE REVIEW

**Comment by saschat** [comment]
@alevy this actually passed the automatic AMI check.

**Comment by saschat** [comment]
Doing this disables the ability to reset the password. We could let the user login via the `cachesight` user which would allow password resetting without being root.

**Comment by alevy** [comment]
What password?

**Comment by saschat** [comment]
Reset the password they set back to the default password. See the docs. I fixed this however in #8

**Comment by alevy** [comment]
@saschat please don't just point me to "the docs" (it's like 10 pages and there are several different _kinds_ of passwords this could be referring to). I guess you mean https://www.cachesight.com/docs#reset-your-password, but you are referring to the _removing_ the cachesight web password and reverting it to the instance ID.

First, I really didn't know what this was referring to and, second, these descriptions documenting design decisions, in pull requests, are important for longevity, when the documentation might be totally different.

**Comment by saschat** [comment]
Sorry, you are totally right.

Was a quick answer on my phone while cooking, maybe not the best idea ;-P

**Pull request merged**
